### ISSUE TITLE
Range or scaling factors of parameters?

### ISSUE THREAD

**Issue by shakfu** [vult-dsp/vult#44]
Just have been playing around with the puredata examples and also looking at the vult and cpp code for each generated external. Everything generates and compiles well. Thanks!

I am assuming that the `process` function's parameters are the parameters for each external. Now are there specific ranges for such parameters? or is there is a convention of some kind operating  such that a real parameter's range is 0.0 to 1.0 and then needs to be scaled? It would be nice to have an explicit range of some kind for each parameter (especially to make sliders, documentation, etc). any clarification would be much appreciated.

**Comment by modlfo** [comment]
There's a short description of the ranges here: https://github.com/modlfo/vult/blob/master/examples/README.md

**Comment by shakfu** [comment]
Thanks very much!

**Comment by shakfu** [comment]
I'll assume that this convention should be followed in general then, for new user-created modules as well.
