### ISSUE TITLE
How to include Vult source ?

### ISSUE THREAD

**Issue by stephanepericat** [vult-dsp/vult#46]
Hi,

When I install the Vult cli with Node.js, and try to compile the sine example with it, I get the following error:

```
vultc -ccode ./src/vult/sine.vult -o sine
Error: ./src/vult/sine.vult:11:6-15: Unknown function 'Util.edge'
   mem trig;
   if(Util.edge(reset > 0.5)) {
      ^^^^^^^^^
```

I'm not sure how to include the Vult source code; please advise.

**Comment by stephanepericat** [comment]
Never mind; the file was not in the same folder ... sorry!

**Comment by modlfo** [comment]
Alternatively, you can pass the flag `-I <dir>` to pass other directories.
